## IMI configuration file
## Documentation @ https://imi.readthedocs.io/en/latest/getting-started/imi-config-file.html

## General
RunName: "on_2019_5mo_buf125"
isAWS: false
UseSlurm: false
SafeMode: false

## Period of interest
StartDate: 20190501
EndDate: 20191001
SpinupMonths: 1

## Region of interest
##   These lat/lon bounds are only used if CreateAutomaticRectilinearStateVectorFile: true
##   Otherwise lat/lon bounds are determined from StateVectorFile
LonMin: -83
LonMax: -78.5
LatMin: 42
LatMax: 44.5

## Use nested grid simulation?
##   Must be "true" for IMI regional inversions
NestedGrid: true

## Select nested grid region (for using pre-cropped meteorological fields)
##   Current options are listed below with ([lat],[lon]) bounds:
##     "AS" : Asia ([-11,55],[60,150]) 
##     "EU" : Europe ([33,61],[-30,70])
##     "NA" : North America ([10,70],[-140,-40])
##     "SA" : South America ([-56,13], [-85,-33])
##     ""   : Use for global met fields (global simulation/custom nested grids)
##   For example, if the region of interest is in Europe ([33,61],[-30,70]), select "EU".
NestedRegion: "NA"

## State vector
CreateAutomaticRectilinearStateVectorFile: true
nBufferClusters: 8
BufferDeg: 1.25
LandThreshold: 0.25

## Custom state vector
StateVectorFile: "/home/ubuntu/integrated_methane_inversion/resources/statevectors/StateVector.nc"
ShapeFile: "/home/ubuntu/integrated_methane_inversion/resources/shapefiles/PermianBasin_Extent_201712.shp"

## Inversion
PriorError: 0.5
ObsError: 15
Gamma: 1.0
PrecomputedJacobian: false

## Grid
##   Select "0.25x0.3125" and "geosfp", or "0.5x0.625" and "merra2"
Res: "0.25x0.3125"
Met: "geosfp"

## Setup modules
##   Turn on/off different steps in setting up the inversion 
SetupTemplateRundir: true
SetupSpinupRun: true
SetupJacobianRuns: true
SetupInversion: true
SetupPosteriorRun: true

## Run modules
##   Turn on/off different steps in performing the inversion
RunSetup: false
DoSpinup: false
DoJacobian: false
DoInversion: false
DoPosterior: true

## IMI preview
DoPreview: false
DOFSThreshold: 0

##====================================================================
##
## Advanced Settings (optional)
##
##====================================================================

## These settings are intended for advanced users who wish to:
##   a. modify additional GEOS-Chem options, or
##   b. run the IMI on a local cluster.
## They can be ignored for any standard cloud application of the IMI.

##--------------------------------------------------------------------
## Additional settings for GEOS-Chem simulations
##--------------------------------------------------------------------

## Jacobian settings
PerturbValue: 1.5

## Apply scale factors from a previous inversion?
UseEmisSF: false
UseOHSF: false

## Save out hourly diagnostics from GEOS-Chem?
## For use in satellite operators via post-processing -- required for TROPOMI
## inversions
HourlyCH4: true

## Turn on planeflight diagnostic in GEOS-Chem?
## For use in comparing GEOS-Chem against planeflight data. The path
## to those data must be specified in input.geos.
PLANEFLIGHT: false

## Turn on old observation operators in GEOS-Chem?
## These will save out text files comparing GEOS-Chem to observations, but have
## to be manually incorporated into the IMI
GOSAT: false
TCCON: false
AIRS: false

##--------------------------------------------------------------------
## Settings for running on a local cluster
##--------------------------------------------------------------------

## Path for IMI runs and output
OutputPath: "/home/rsb001/sitestore/geoschem/imi_output_dir"

## Path to GEOS-Chem input data
DataPath: "/home/rsb001/sitestore/geoschem/ExtData"

## Environment files
CondaFile: "/home/ubuntu/miniconda/etc/profile.d/conda.sh"
CondaEnv: "geo"

## Download initial restart file from AWS S3?
RestartDownload: false

## Path to initial GEOS-Chem restart file + prefix
##   ("YYYYMMDD_0000z.nc4" will be appended)
RestartFilePrefix: "/home/rsb001/sitestore/geoschem/4x5_ch4_2019/Restarts/GEOSChem.Restart."
RestartFilePreviewPrefix: "/home/rsb001/sitestore/geoschem/4x5_ch4_2019/Restarts/GEOSChem.Restart."

## Path to GEOS-Chem boundary condition files (for nested grid simulations)
BCpath: "/home/rsb001/sitestore/geoschem/4x5_ch4_2019/OutputDir"

## Options to download missing GEOS-Chem input data from AWS S3
##   NOTE: You will be charged if your ec2 instance is not in the
##         us-east-1 region.
PreviewDryRun: false
SpinupDryrun: false
ProductionDryRun: false
PosteriorDryRun: false
BCdryrun: false
